#pragma once

// Please don't change the content of this header, it is auto generated by CMAKE

#define PROJECT_SOURCE_DIR "C:/Users/dddnn/Desktop/2021 W2/CS 427/team project/milestone 3/Vertigo/Vertigo/"
